name       : xauth
version    : '1.1'
release    : 5
source     :
    - https://xorg.freedesktop.org/releases/individual/app/xauth-1.1.tar.gz : e9fce796c8c5c9368594b9e8bbba237fb54b6615f5fd60e8d0a5b3c52a92c5ef
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xauth
description: |
    The xauth command is usually used to edit and display the authorization information used in connecting to the X server. This program extracts authorization records from one machine and merge them into another (for example, when using remote logins or granting access to other users).
builddeps  :
    - pkgconfig(xau)
    - pkgconfig(xmuu)
    - pkgconfig(xext)
    - pkgconfig(x11)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
