name       : xauth
version    : 1.0.10
release    : 4
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xauth-1.0.10.tar.bz2 : 5afe42ce3cdf4f60520d1658d2b17face45c74050f39af45dccdc95e73fafc4d
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xauth
builddeps  :
    - pkgconfig(xau)
    - pkgconfig(xmuu)
    - pkgconfig(xext)
    - pkgconfig(x11)
description: |
    X.Org Applications - xauth
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
